site_name: Cello - The engine for cloud deployments
repo_url: https://github.com/cello-proj/cello
strict: true
theme:
  name: material
  palette:
    primary: blue
  font:
    text: Work Sans
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Quick Start: quickstart.md
  - User Guide:
      - Beginner:
          - Core Concepts: users/coreconcepts.md
          - CLI: users/cli.md
      - Environment Variables: users/envvars.md
      - Examples: https://github.com/cello-proj/cello/blob/master/examples/README.md
      - CLI Reference:
          - cello: cli/cello.md
          - cello sync: cli/cello_sync.md
          - cello diff: cli/cello_diff.md
          - cello get: cli/cello_get.md
          - cello list: cli/cello_list.md
          - cello workflow: cli/cello_workflow.md
          - cello logs: cli/cello_logs.md
  - Developer Guide:
      - Local Development Environment: developers/development-env.md
      - Contributing: developers/CONTRIBUTING.md
      - Static Code Analysis: developers/static-code-analysis.md
      - API: developers/api.md
      - Releasing: developers/releasing.md
  - FAQ: faq.md
  - Releases ⧉: https://github.com/cello-proj/cello/releases
  - Roadmap: roadmap.md
  - Appendix: appendix.md
